name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 10
    concurrency:
      group: frontend-ci-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache disabled to avoid path resolution issues (no lockfile)

      - name: Install deps
        run: npm --prefix hka-frontend install --no-audit --no-fund --legacy-peer-deps --silent

      - name: Type check
        run: |
          node "$GITHUB_WORKSPACE/hka-frontend/node_modules/typescript/bin/tsc" -p "$GITHUB_WORKSPACE/hka-frontend/tsconfig.json" --noEmit --pretty false

      - name: Build
        run: npm --prefix hka-frontend run build
