name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  preflight-pages:
    name: Check Pages enabled
    runs-on: ubuntu-latest
    outputs:
      enabled: ${{ steps.check.outputs.enabled }}
    steps:
      - name: Check if GitHub Pages is enabled
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            let enabled = false;
            try {
              await github.rest.repos.getPages({ owner, repo });
              enabled = true;
            } catch (e) {
              enabled = false;
              core.info('GitHub Pages not enabled yet (expected on first setup).');
            }
            core.setOutput('enabled', String(enabled));

  build:
    timeout-minutes: 10
    concurrency:
      group: frontend-ci-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hka-frontend
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache disabled to avoid path resolution issues (no lockfile)

      # Prepare GitHub Pages configuration (required by deploy-pages)
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install deps
        run: npm install --no-audit --no-fund --legacy-peer-deps --silent

      - name: Type check
        run: |
          ls -la
          node ./node_modules/typescript/bin/tsc -p ./tsconfig.json --noEmit --pretty false

      - name: Build
        run: npm run build

      # Upload build as a generic artifact for PRs/manual inspection
      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: hka-frontend/dist

      # Prepare artifact for GitHub Pages (consumed by deploy job)
      - name: Upload Pages artifact
        if: success()
        uses: actions/upload-pages-artifact@v3
        with:
          path: hka-frontend/dist

  # Slack notification is optional; omitted here to keep workflow lint-clean.

  deploy:
    name: Deploy to GitHub Pages
    needs: [build, preflight-pages]
    runs-on: ubuntu-latest
  if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.preflight-pages.outputs.enabled == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: frontend-pages-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

  pages-deploy-skip-note:
    name: Pages deploy skipped
    needs: [build, preflight-pages]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.preflight-pages.outputs.enabled != 'true'
    steps:
      - name: Explain skip
        run: |
          echo "## GitHub Pages deploy skipped" >> "$GITHUB_STEP_SUMMARY"
          echo "GitHub Pages belum aktif untuk repo ini." >> "$GITHUB_STEP_SUMMARY"
          echo "Aktifkan dengan salah satu opsi berikut:" >> "$GITHUB_STEP_SUMMARY"
          echo "- Ubah repository menjadi Public (Settings → General → Change repository visibility)" >> "$GITHUB_STEP_SUMMARY"
          echo "- Upgrade ke GitHub Pro/Team/Enterprise untuk Pages di private repo" >> "$GITHUB_STEP_SUMMARY"
          echo "Setelah aktif, re-run workflow; job deploy akan jalan otomatis." >> "$GITHUB_STEP_SUMMARY"
